trying again

diff --git a/clusters/main/kubernetes/media/qbittorrent/app/helm-release.yaml b/clusters/main/kubernetes/media/qbittorrent/app/helm-release.yaml
--- a/clusters/main/kubernetes/media/qbittorrent/app/helm-release.yaml
+++ b/clusters/main/kubernetes/media/qbittorrent/app/helm-release.yaml
@@ -234,30 +234,30 @@ spec:
                   done
 
 
-        containers:
-            mam-updater:
-              enabled: true
-              primary: false
-              imageSelector: mamUpdaterImage
-              command:
-                - /bin/sh
-                - -c
+        # containers:
+        #     mam-updater:
+        #       enabled: true
+        #       primary: false
+        #       imageSelector: mamUpdaterImage
+        #       command:
+        #         - /bin/sh
+        #         - -c
              
-              args:
-                - |
-                  set -e
-                  apk add --no-cache curl coreutils jq
-                  chmod +x /config/mam-script-with-jq.sh
+        #       args:
+        #         - |
+        #           set -e
+        #           apk add --no-cache curl coreutils jq
+        #           chmod +x /config/mam-script-with-jq.sh
 
-                  # initial heartbeat
-                  date -Iseconds > /tmp/mam-updater.heartbeat
+        #           # initial heartbeat
+        #           date -Iseconds > /tmp/mam-updater.heartbeat
 
-                  while true; do
-                    echo "[mam-updater] running at $(date -Iseconds)"
-                    /config/config/mam-script-with-jq.sh|| echo "[mam-updater] script failed with $?"
-                    date -Iseconds > /tmp/mam-updater.heartbeat
-                    sleep 3600
-                  done
+        #           while true; do
+        #             echo "[mam-updater] running at $(date -Iseconds)"
+        #             /config/config/mam-script-with-jq.sh|| echo "[mam-updater] script failed with $?"
+        #             date -Iseconds > /tmp/mam-updater.heartbeat
+        #             sleep 3600
+        #           done
               # args:
               #   - |
               #     set -e
